# Solving Linear Systems: 3 variables

In [1]:
import numpy as np

## 1. Representing and Solving a System of Linear Equations using Matrices
3 variable linear system:

$$\begin{cases} 
4x_1-3x_2+x_3=-10, \\ 2x_1+x_2+3x_3=0, \\ -x_1+2x_2-5x_3=17, \end{cases}\tag{1}$$

Solving this system of equations means finding the values of , $x_1$, $x_2$, $x_3$ that will satisfy all 3 equations.
Let's create the matrix to solve the system of equations with numpy.

In [2]:
coeff = np.array([[4, -3, 1],
                  [2, 1, 3],
                  [-1, 2, -5]],
                  dtype=np.dtype(float))

const = np.array([-10, 0, 17], dtype=np.dtype(float))

print("Coefficient Matrix:")
print(coeff)
print("\nConst Array:", const)

Coefficient Matrix:
[[ 4. -3.  1.]
 [ 2.  1.  3.]
 [-1.  2. -5.]]

Const Array: [-10.   0.  17.]


In [3]:
print("Shape of coefficient matrix:", coeff.shape)
print("Shape of const array:", const.shape)

Shape of coefficient matrix: (3, 3)
Shape of const array: (3,)


Let's find the solution for this system using *__np.linalg.solve()__*:

In [4]:
solution = np.linalg.solve(coeff, const)

print("Solution x1, x2 and x3:", solution)

Solution x1, x2 and x3: [ 1.  4. -2.]


Let's calculate the determinant using `np.linalg.det(A)` function:

In [5]:
det = np.linalg.det(coeff)

print("Determinant of the system:", det)

Determinant of the system: -60.000000000000036


## 2. Solving System of Linear Equations using Row Reduction
Although in mathematical concept the solution of a system is done manually, this process is easier in programming. The solution of a system is also possible with the row reduction method. In order to apply the row reduction method, let's stack the coefficient and constant matrix with *__np.hstack()__*.


In [6]:
system = np.hstack((coeff, const.reshape(3,1)))

print("System:")
print(system)

System:
[[  4.  -3.   1. -10.]
 [  2.   1.   3.   0.]
 [ -1.   2.  -5.  17.]]


Performing some basic operations on the matrices does not change the system solution.
- Multiply any row by a non-zero number
- Add two rows and exchange one of the original rows with the result of the addition
- Swap rows

We may need to perform these operations several times in very large matrices.

In [7]:
def MultiplyRow(matrix, row_num, row_num_multiple):
    new_matrix = matrix.copy()
    new_matrix[row_num] = new_matrix[row_num] * row_num_multiple
    return new_matrix

print("Original Matrix:")
print(system)
print("\nMatrix after its third row is multiplied by 2:")
print(MultiplyRow(system, 2, 2))

Original Matrix:
[[  4.  -3.   1. -10.]
 [  2.   1.   3.   0.]
 [ -1.   2.  -5.  17.]]

Matrix after its third row is multiplied by 2:
[[  4.  -3.   1. -10.]
 [  2.   1.   3.   0.]
 [ -2.   4. -10.  34.]]


In [8]:
def AddRows(matrix, row_num_1, row_num_2, row_num_multiple):
    new_matrix = matrix.copy()
    new_matrix[row_num_2] = row_num_multiple * new_matrix[row_num_1] + new_matrix[row_num_2]
    return new_matrix

print("Original Matrix:")
print(system)
print("\nMatrix after exchange of the third row with the sum of itself and second row multiplied by 1/2:")
print(AddRows(system, 1, 2, 1/2))

Original Matrix:
[[  4.  -3.   1. -10.]
 [  2.   1.   3.   0.]
 [ -1.   2.  -5.  17.]]

Matrix after exchange of the third row with the sum of itself and second row multiplied by 1/2:
[[  4.   -3.    1.  -10. ]
 [  2.    1.    3.    0. ]
 [  0.    2.5  -3.5  17. ]]


In [9]:
def SwapRows(matrix, row_num_1, row_num_2):
    new_matrix = matrix.copy()
    new_matrix[[row_num_1, row_num_2]] = new_matrix[[row_num_2, row_num_1]]
    return new_matrix

print("Original Matrix:")
print(system)
print("\nMatrix after exchange its first and third rows:")
print(SwapRows(system, 0, 2))

Original Matrix:
[[  4.  -3.   1. -10.]
 [  2.   1.   3.   0.]
 [ -1.   2.  -5.  17.]]

Matrix after exchange its first and third rows:
[[ -1.   2.  -5.  17.]
 [  2.   1.   3.   0.]
 [  4.  -3.   1. -10.]]


We can use the operations we have defined for row reduction. In order to do this in the manual solution, we must set the first element of the first row to 1 or -1. This is of no use when calculating with Python, but let's calculate it for convenience.

In [10]:
new_matrix = SwapRows(system, 0, 2)

print(new_matrix)

[[ -1.   2.  -5.  17.]
 [  2.   1.   3.   0.]
 [  4.  -3.   1. -10.]]


Let's continue with some elementary operations. The first elements of the second and third rows must be 0.

In [11]:
new_matrix = AddRows(new_matrix, 0, 1, 2)

print(new_matrix)

[[ -1.   2.  -5.  17.]
 [  0.   5.  -7.  34.]
 [  4.  -3.   1. -10.]]


In [12]:
new_matrix = AddRows(new_matrix, 0, 2, 4)

print(new_matrix)

[[ -1.   2.  -5.  17.]
 [  0.   5.  -7.  34.]
 [  0.   5. -19.  58.]]


We must set the second element of the third row to 0.

In [13]:
new_matrix = AddRows(new_matrix, 1, 2, -1)

print(new_matrix)

[[ -1.   2.  -5.  17.]
 [  0.   5.  -7.  34.]
 [  0.   0. -12.  24.]]


It is easy now to find the value of $x_3$ from the third row, as it corresponds to the equation $-12x_3=24$. Let's divide the row by -12:

In [14]:
new_matrix = MultiplyRow(new_matrix, 2, -1/12)

print(new_matrix)

[[-1.  2. -5. 17.]
 [ 0.  5. -7. 34.]
 [-0. -0.  1. -2.]]


In [15]:
x3 = -2
x2 = (new_matrix[1, 3] - new_matrix[1, 2] * x3) / new_matrix[1, 1]
x1 = (new_matrix[0, 3] - new_matrix[0, 2] * x3 - new_matrix[0, 1] * x2) / new_matrix[0, 0]

print(x1, x2, x3)

1.0 4.0 -2


## 3. Systems of Linear Equations with No Solutions
Given another system of linear equations:

$$\begin{cases} 
x_1+x_2+x_3=2, \\ x_2-3x_3=1, \\ 2x_1+x_2+5x_3=0, \end{cases}\tag{2}$$

let's find the determinant of the corresponding matrix.

In [16]:
coeff = np.array([[1, 1, 1],
                  [0, 1, -3],
                  [2, 1, 5]], dtype=np.dtype(float))

const = np.array([2, 1, 0], dtype=np.dtype(float))

det = np.linalg.det(coeff)

print("Determinant of the system:", det)

Determinant of the system: 0.0


Since the determinant of the matrix is 0, the system does not have a unique solution. The matrix is singular, has either infinitely many solutions or no solutions.

In [17]:
solution = np.linalg.solve(coeff, const)
print(solution)

LinAlgError: Singular matrix

In [18]:
system = np.hstack((coeff, const.reshape(3,1)))
print(system)

[[ 1.  1.  1.  2.]
 [ 0.  1. -3.  1.]
 [ 2.  1.  5.  0.]]


In [19]:
new_matrix = AddRows(system, 0, 2, -2)
print(new_matrix)

[[ 1.  1.  1.  2.]
 [ 0.  1. -3.  1.]
 [ 0. -1.  3. -4.]]


In [20]:
new_matrix = AddRows(new_matrix, 1, 2, 1)
print(new_matrix)

[[ 1.  1.  1.  2.]
 [ 0.  1. -3.  1.]
 [ 0.  0.  0. -3.]]


The last row will correspond to the equation  0=−3 which has no solution. 

## 4 - System of Linear Equations with Infinite Number of Solutions

You can bring system $(2)$ to consistency by changing only the free coefficients:

$$\begin{cases} 
x_1+x_2+x_3=2, \\ x_2-3x_3=1, \\ 2x_1+x_2+5x_3=3. \end{cases}\tag{3}$$

Define the new array of free coefficients:

In [21]:
coeff = np.array([[1, 1, 1],
                  [0, 1, -3],
                  [2, 1, 5]], dtype=np.dtype(float))

const = np.array([2, 1, 3], dtype=np.dtype(float))

system = np.hstack((coeff, const.reshape(3,1)))
print(system)

[[ 1.  1.  1.  2.]
 [ 0.  1. -3.  1.]
 [ 2.  1.  5.  3.]]


In [22]:
new_matrix = AddRows(system, 0, 2, -2)
print(new_matrix)

[[ 1.  1.  1.  2.]
 [ 0.  1. -3.  1.]
 [ 0. -1.  3. -1.]]


In [23]:
new_matrix = AddRows(new_matrix, 1, 2, 1)
print(new_matrix)

[[ 1.  1.  1.  2.]
 [ 0.  1. -3.  1.]
 [ 0.  0.  0.  0.]]


Thus from the corresponding linear system

$$\begin{cases} 
x_1+x_2+x_3=2, \\ x_2-3x_3=1, \\ 0=0, \end{cases}\tag{4}$$

you can find that $x_2=1+3x_3$, substitute it into the first equation and find $x_1$. Thus the solutions of the linear system $(3)$ are:

$$\begin{cases} 
x_1=1-4x_3, \\ x_2=1+3x_3, \end{cases}\tag{5}$$

where $x_3$ is any real number.