# MATRIX MULTIPLICATION

In [1]:
import numpy as np

In [2]:
A = np.array([[4,9,9], [9,1,6], [9,2,3]])
print("Matrix A (3 by 3): \n", A)

B = np.array([[2,2], [5,7], [4,4]])
print("Matrix B (3 by 2): \n", B)

Matrix A (3 by 3): 
 [[4 9 9]
 [9 1 6]
 [9 2 3]]
Matrix B (3 by 2): 
 [[2 2]
 [5 7]
 [4 4]]


Matrix multiplication is performed with np.matmul().

In [11]:
np.matmul(A, B)

array([[ 89, 107],
       [ 47,  49],
       [ 40,  44]])

We can also perform this operation with the @ operand.

In [4]:
A @ B

array([[ 89, 107],
       [ 47,  49],
       [ 40,  44]])

In order to perform matrix multiplication, the number of columns of matrix A must be equal to the number of rows of matrix B. Otherwise, matrix multiplication cannot be performed. For example, if we swap the matrix A and matrix B:

In [6]:
try:
    np.matmul(B, A)
except ValueError as err:
    print(err)

matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)


In [7]:
try:
    B @ A
except ValueError as err:
    print(err)

matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)


In [10]:
x = np.array([1, -2, -5])
y = np.array([4, 3, -1])
print("Shape of vector y:", y.shape)

print("Shape of vector x:", x.shape)
print("Number of dimensions of vector x:", x.ndim)
print("Shape of vector x, reshaped to a matrix:", x.reshape((3, 1)).shape)
print("Number of dimensions of vector x, reshaped to a matrix:", x.reshape((3, 1)).ndim)

Shape of vector y: (3,)
Shape of vector x: (3,)
Number of dimensions of vector x: 1
Shape of vector x, reshaped to a matrix: (3, 1)
Number of dimensions of vector x, reshaped to a matrix: 2


In [9]:
np.matmul(x, y)

3

We did not get any errors in the above command because what actually happened is dot product. Python automatically performs (1,3) multiplication by transposing the x matrix x.

In [12]:
try:
    np.matmul(x.reshape((3, 1)), y.reshape((3, 1)))
except ValueError as err:
    print(err)

matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 1)


The np.dot() function also works as matrix multiplication for matrices.

In [13]:
np.dot(A, B)

array([[ 89, 107],
       [ 47,  49],
       [ 40,  44]])

Let's also look at an example of scalar subtraction:

In [14]:
A - 2

array([[ 2,  7,  7],
       [ 7, -1,  4],
       [ 7,  0,  1]])

Python also automatically creates a matrix with 2 scalars of the same size as the matrix and performs the element by element operation.